# Generated by Django 2.2.4 on 2019-08-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
