# Generated by Django 2.2.4 on 2019-08-19 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=300)),
                ('Pan_No', models.CharField(max_length=100)),
                ('Regd_No', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=300)),
                ('Mobile', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Web', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Logo', models.CharField(max_length=300)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
